import os
import re
from fastapi import FastAPI, HTTPException, Depends, Header
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv
from langchain_groq import ChatGroq

from rag.pipelines.sql_rag import sql_rag_chain
from rag.pipelines.hybrid_rag import hybrid_rag_chain

load_dotenv()

app = FastAPI(title="MediBot API")

# Configure CORS so your Next.js frontend can communicate with FastAPI
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, restrict this to your Next.js domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# LLM to classify questions (analytical vs document)
llm = ChatGroq(
    model=os.getenv("GROQ_MODEL"),
    temperature=0,
    groq_api_key=os.getenv("GROQ_API_KEY")
)

# Demo User Accounts (mapping username -> password & role)
USER_DB = {
    "dr.mehta": {"password": "password", "role": "doctor"},
    "nurse.priya": {"password": "password", "role": "nurse"},
    "billing.ravi": {"password": "password", "role": "billing_executive"},
    "tech.anand": {"password": "password", "role": "technician"},
    "admin.sys": {"password": "password", "role": "admin"},
}

# Role-to-Collections Access Matrix
ROLE_COLLECTIONS = {
    "doctor": ["clinical", "nursing", "general"],
    "nurse": ["nursing", "general"],
    "billing_executive": ["billing", "general"],
    "technician": ["equipment", "general"],
    "admin": ["general", "clinical", "nursing", "billing", "equipment"]
}

class LoginRequest(BaseModel):
    username: str
    password: str

class ChatRequest(BaseModel):
    question: str

def get_role_from_token(authorization: str = Header(None)) -> str:
    if not authorization or not authorization.startswith("Bearer"):
        raise HTTPException(status_code = 401, detail = "Missing or invalid Authorization token")

        # sample token generated by "/login" endpoint will be something like "Bearer session-123-nurse"
        # Extracting role from the token
    try:
        token_content = authorization.split(" ")[1] # ignore the Bearer string
        parts = token_content.split("-")

        if len(parts) < 3 or parts[0] != "session":
            raise HTTPException(status_code = 401, detail = "Invalid token format")
        
        role = parts[-1]
        if role not in ROLE_COLLECTIONS:
            raise HTTPException(status_code = 401, detail = "Invalid role in token")

        return role
    except Exception as e:
        raise HTTPException(status_code = 401, detail = "Invalid token")

@app.post("/login")
def login(req: LoginRequest):
    user = USER_DB.get(req.username.lower())
    if not user or user.get("password") != req.password:
        raise HTTPException(status_code = 401, detail = "Invalid credentials")
    
    role = user.get("role")
    token = f"session-{req.username.lower()}-{role}"
    return {
        "token": token,
        "role": role,
        "username": req.username.lower()
    }

@app.get("/collections/{role}")
def get_collections(role: str):
    collections = ROLE_COLLECTIONS.get(role.lower())
    if collections is None:
        raise HTTPException(status_code = 404, detail = "Role not found")
    return collections

@app.post("/chat")
def chat(req: ChatRequest, role: str = Depends(get_role_from_token)):
    classify_prompt = f"""Analyze the user's question and determine if it is an analytical or quantitative question asking for statistics, database counts, sums, or calculations on claims or maintenance tickets.
        Answer with only 'YES' or 'NO' and nothing else.
        Question: {req.question}
        Analytical:"""

        
    try:
        classification = llm.invoke(classify_prompt).content.strip().upper()
        is_analytical = "YES" in classification
    except Exception:
        is_analytical = False # Do document search 

    if is_analytical:
        if role.lower() not in ["admin", "billing_executive"]:
            access_denied_msg = f"Sorry, {role.replace('_', ' ')}, you do not have access to perform quantitative analysis."
            return {
                "answer": access_denied_msg,
                "sources": [],
                "retrieval_type": "sql_rag",
                "role": role
            }
        sql_response = sql_rag_chain(query=req.question, role=role)
        return {
            "answer": sql_response,
            "sources": [],
            "retrieval_type": "sql_rag",
            "role": role
        }

    else:
        hybrid_response = hybrid_rag_chain(query=req.question, role=role)
        return hybrid_response



@app.get("/health")
def health():
    return {"status": "Healthy as a horse"}

    
    